### ISSUE TITLE
CNPC-EpicFight-Integration crash

### ISSUE THREAD

**Issue by Ozen-Ray** [Goodbird-git/CNPC-EpicFight-Addon#2]
CNPC-EpicFight-Integration crash on mod loading.

CNPC-EpicFight-Integration version 1.20.1.20240804
CustomNPCs-Unofficial version : 1.20.1-GBPort-Unnoficial-20240709
EpicFight version : 20.8.9-1.20.1

Log:

[crash-2024-08-12_09.05.18-fml.txt](https://github.com/user-attachments/files/16582050/crash-2024-08-12_09.05.18-fml.txt)

**Comment by Goodbird-git** [comment]
Sorry for the late responce
The EpicFight addon is now updated to the latest EpicFight version
https://www.curseforge.com/minecraft/mc-mods/cnpc-epicfight-integration/files/5652873
