### ISSUE TITLE
Epic Fight has failed to load correctly

### ISSUE THREAD

**Issue by MkUltra2000** [Goodbird-git/CNPC-EpicFight-Addon#3]
Hey I was wondering if you could help with this issue or point me in the correct direction if not.

Created a new curseforge creation 1.20.1 forge - 47.3.0.
With Mods: 
Epic fight 20.8.9-1.20.1
CustomNPCs-Unofficial 1.20.1
CNPC-EpicFight-Integration 1.20.1.20240804

As the only mods expecting this to work without any hitches however can't seem to get to the main title screen hitting this Epic Fight has failed to load correctly. 

I glanced over the crash logs maybe it has something with this line but I am no java specialist :
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching entityRendererProvider:Ljava/util/Map;

Below is the crash report and log files please let me know if there is anything else I can provide to help pinpoint the issue as I would love to use these mods in tangent with each other.
[latest.log](https://github.com/user-attachments/files/16627765/latest.log)

[crash-2024-08-15_17.56.05-fml.txt](https://github.com/user-attachments/files/16627757/crash-2024-08-15_17.56.05-fml.txt)

**Comment by Ozen-Ray** [comment]
CNPC Epicfight - addon is outdated for the current EpicFight version  sadly and the creator don't answer

**Comment by MkUltra2000** [comment]
I see this addon is awaiting for the creator input, ( would be interested why their input is needed like if it's to make the code compatible or get permission ect... ) Don't think there too much I can do then. Either way thank you for your time and help :) .

**Comment by Goodbird-git** [comment]
Sorry for the late responce
The addon is now updated to the latest version of EpicFight
https://www.curseforge.com/minecraft/mc-mods/cnpc-epicfight-integration/files/5652873
