### ISSUE TITLE
[1.20.1] Crash on Dedicated Server

### ISSUE THREAD

**Issue by Talan67** [Goodbird-git/CNPC-EpicFight-Addon#4]
I initially reported this on Mohist Github found here: https://github.com/MohistMC/Mohist/issues/3322, as an issue on there end but apparently its this mod. I have now tested this via Forge 47.3.7 and got the same crash shortly after start up, more details of the issue are mentioned on the original Mohist Github issue.

Heres logs just in case:  https://gist.github.com/Talan67/147f075bdc966e5b14d177e95815950e
                                     https://gist.github.com/Talan67/af9c0bf84e043549408c7b6ef0de3dd8

**Comment by Goodbird-git** [comment]
That will be fixed in the next update

**Comment by Goodbird-git** [comment]
There is now a version that should be compatible with servers
https://www.curseforge.com/minecraft/mc-mods/cnpc-epicfight-integration/files/5667558
