### ISSUE TITLE
Bow animation? (Question)

### ISSUE THREAD

**Issue by SchlangeGoto** [Goodbird-git/CNPC-EpicFight-Addon#5]
Hey how can i make that the Bow Animation is normal? Right know the Bow has no Animation

https://github.com/user-attachments/assets/36d763db-8737-4846-8a55-70f13588c978

**Comment by Goodbird-git** [comment]
Right now there is no option for making bow animations, because CNPCs can shoot arrows (and not even arrows) without needing a bow. 
But you can add set idle animation as bow aiming for npcs holding the bow and it should partially work
